### ISSUE TITLE
Create tests for the Google maps screen

### ISSUE THREAD

**Issue by Jeremmmyyyyy** [EPFL-SwEnt-2024-LaStartUp/TripTracker#40]

**Comment by JCHAVEROT** [comment]
During Sprint 3, Loïc and I worked on testing the google map screen. Though we encountered several difficulties:

- App flow: while testing, we need to go through the main flow for the app until reaching the google map screen (login -> home -> map). However during this process we need to sign in with Google and to grant user location permission. These were appearing in an undeterministic manner, not at all or not at the same place.
- Previews: we tried to test previews screen, but we got cloud firebase errors.
- MockK: we tried mocking what was needed by the google map screen outside of it, but this resulted in a proxy error.

As a result, we will continue this during the next sprint.

**Comment by JCHAVEROT** [comment]
Note that this issue was addressed over two sprints because of technical difficulties (hence the high amount of hours).
